name: Publish NPM package\

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true 

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        run: npm install -g pnpm

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish
        run: npm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}